/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp.dsw.view;

import java.util.List;

import com.mycompany.tp.dsw.dao.BebidaDao;
import com.mycompany.tp.dsw.dao.ItemMenuDao;
import com.mycompany.tp.dsw.dao.PlatoDao;
import com.mycompany.tp.dsw.memory.BebidaMemory;
import com.mycompany.tp.dsw.memory.ItemMenuMemory;
import com.mycompany.tp.dsw.memory.PlatoMemory;
import com.mycompany.tp.dsw.model.Plato;
import com.mycompany.tp.dsw.model.Bebida;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmItemMenu2 extends javax.swing.JFrame {

    private final PlatoDao platoDao;
    private final BebidaDao bebidaDao;
    private final Integer idVendedor;

    public FrmItemMenu2(PlatoDao platoDao, BebidaDao bebidaDao, String idVendedor, String nombreVendedor) {
        initComponents();
        this.setTitle("Item Menu");
        this.setLocationRelativeTo(null);

        this.setSize(750, 460);
        this.setResizable(false);
        this.platoDao = platoDao;
        this.bebidaDao = bebidaDao;
        this.idVendedor = Integer.parseInt(idVendedor);
        jLabelVendedorData.setText("Vendedor: " + nombreVendedor + " ID: " + idVendedor);
        inicializarTabla();
    }

    private void inicializarTabla() {
        // Obtiene el valor por defecto del JComboBox
        String defaultItem = (String) jComboBoxPlatoBebida.getSelectedItem();

        if ("Plato".equals(defaultItem)) {
            List<Plato> platos = platoDao.obtenerTodosLosPlatos();
            mostrarPlatoEnPantalla(platos);
        } else if ("Bebida".equals(defaultItem)) {
            List<Bebida> bebidas = bebidaDao.obtenerTodasLasBebidas();
            mostrarBebidaEnPantalla(bebidas);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEliminarItem = new javax.swing.JButton();
        btnAgregarItem = new javax.swing.JButton();
        btnModificarItem = new javax.swing.JButton();
        btnBuscarItem = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jComboBoxPlatoBebida = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItemDatos = new javax.swing.JTable();
        btnVerDetalles = new javax.swing.JButton();
        jLabelVendedorData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(715, 397));

        btnEliminarItem.setText("Eliminar Item");
        btnEliminarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarItemActionPerformed(evt);
            }
        });

        btnAgregarItem.setText("Agregar Item");
        btnAgregarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarItemActionPerformed(evt);
            }
        });

        btnModificarItem.setText("Modificar Item");
        btnModificarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarItemActionPerformed(evt);
            }
        });

        btnBuscarItem.setText("Buscar Item");
        btnBuscarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarItemActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jComboBoxPlatoBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plato", "Bebida" }));
        jComboBoxPlatoBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlatoBebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarItem, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnModificarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPlatoBebida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jComboBoxPlatoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbItemDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbItemDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItemDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbItemDatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 500, 321));

        btnVerDetalles.setText("Ver Detalles");
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));
        jPanel2.add(jLabelVendedorData, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 356, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarItemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnEliminarItemActionPerformed

    private void btnAgregarItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarItemActionPerformed
        String tipoItemMenu = jComboBoxPlatoBebida.getSelectedItem().toString();

        FachadaItemMenu selector = new FachadaItemMenu();

    }

    }// GEN-LAST:event_btnAgregarItemActionPerformed

    private void btnModificarItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnModificarItemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnModificarItemActionPerformed

    private void btnBuscarItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarItemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnBuscarItemActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }// GEN-LAST:event_btnSalirActionPerformed

    private void tbItemDatosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbItemDatosMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_tbItemDatosMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedItem = (String) jComboBoxPlatoBebida.getSelectedItem();
        if ("Plato".equals(selectedItem)) {
            List<Plato> platos = platoDao.obtenerTodosLosPlatos();
            mostrarPlatoEnPantalla(platos);
        } else if ("Bebida".equals(selectedItem)) {
            List<Bebida> bebidas = bebidaDao.obtenerTodasLasBebidas();
            mostrarBebidaEnPantalla(bebidas);
        }
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVerDetallesActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnVerDetallesActionPerformed

    private void mostrarBebidaEnPantalla(List<Bebida> listaBebida) {
        DefaultTableModel model;
        String[] titulo = { "ID", "NOMBRE", "VOLUMEN", "DESCRIPCION", "PRECIO" };
        model = new DefaultTableModel(null, titulo);

        if (listaBebida.isEmpty()) {
            // Si la lista está vacía, puedes decidir no añadir filas.
            // Esto vacía la tabla.
            tbItemDatos.setModel(model); // Modelo vacío
        } else {
            for (Bebida bebida : listaBebida) {
                Object[] fila = new Object[5]; // Número de columnas

                // Asigna valores a cada columna de la fila
                fila[0] = bebida.getId();
                fila[1] = bebida.getNombre();
                fila[2] = bebida.getVolumen();
                fila[3] = bebida.getDescripcion();
                fila[4] = bebida.getPrecio();

                // Añade la fila al modelo de la tabla
                model.addRow(fila);
            }
            tbItemDatos.setModel(model);
        }
    }

    private void mostrarPlatoEnPantalla(List<Plato> listaPlatos) {
        DefaultTableModel model;
        String[] titulo = { "ID", "NOMBRE", "CALORIAS", "DESCRIPCION", "PRECIO" };
        model = new DefaultTableModel(null, titulo);

        if (listaPlatos.isEmpty()) {
            // Si la lista está vacía, puedes decidir no añadir filas.
            // Esto vacía la tabla.
            tbItemDatos.setModel(model); // Modelo vacío
        } else {
            for (Plato plato : listaPlatos) {
                Object[] fila = new Object[5]; // Número de columnas

                // Asigna valores a cada columna de la fila
                fila[0] = plato.getId();
                fila[1] = plato.getNombre();
                fila[2] = plato.getCalorias();
                fila[3] = plato.getDescripcion();
                fila[4] = plato.getPrecio();

                // Añade la fila al modelo de la tabla
                model.addRow(fila);
            }
            tbItemDatos.setModel(model);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmItemMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmItemMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmItemMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmItemMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmItemMenu2(new PlatoMemory(), new BebidaMemory(), "id", "nombre").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarItem;
    private javax.swing.JButton btnBuscarItem;
    private javax.swing.JButton btnEliminarItem;
    private javax.swing.JButton btnModificarItem;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JComboBox<String> jComboBoxPlatoBebida;
    private javax.swing.JLabel jLabelVendedorData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbItemDatos;
    // End of variables declaration//GEN-END:variables
}
