/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp.dsw.view;

import com.mycompany.tp.dsw.dao.ItemMenuDao;
import com.mycompany.tp.dsw.memory.ItemMenuMemory;
import com.mycompany.tp.dsw.model.Plato;
import java.math.BigDecimal;

/**
 *
 * @author Usuario
 */
public class FrmModificarPlato extends javax.swing.JFrame {

    Plato plato;
    ItemMenuDao itemMenuDao;

    public FrmModificarPlato() {
        initComponents();
    }

    public FrmModificarPlato(Plato plato) {
        initComponents();
        this.setTitle("Modificar Plato");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        ItemMenuDao itemMenuDao = new ItemMenuMemory();

        this.plato = plato;

        // Asignar los valores de la instancia a los campos
        txtID.setEnabled(false);
        txtID.setText(plato.getId().toString());
        txtNombre.setText(plato.getNombre());
        txtPeso.setText(plato.getPeso().toString());
        txtPrecio.setText(plato.getPrecio().toString());
        if (plato.getAptoCeliaco()) {
            jCheckBoxCeliaco.setSelected(true);
        }
        if (plato.getAptoVegano()) {
            jCheckBoxVegano.setSelected(true);
        }
        if (plato.getAptoVegetariano()) {
            jCheckBoxVegetariano.setSelected(true);
        }
        txtCalorias.setText(plato.getCalorias().toString());
        jTextAreaDescripcion.setText(plato.getDescripcion());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelFechaAlta = new javax.swing.JLabel();
        jCheckBoxVegano = new javax.swing.JCheckBox();
        jCheckBoxCeliaco = new javax.swing.JCheckBox();
        jCheckBoxVegetariano = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCalorias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(440, 260));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Precio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, -1));

        txtPeso.setForeground(new java.awt.Color(51, 51, 51));
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, -1));

        txtPrecio.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 150, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 150, -1));

        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 220, -1));

        jLabel4.setText("Peso:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, -1));

        txtID.setForeground(new java.awt.Color(51, 51, 51));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, -1));

        jLabel6.setText("ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, -1));
        jPanel1.add(jLabelFechaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jCheckBoxVegano.setText("Apto Vegano");
        jCheckBoxVegano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVeganoActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxVegano, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jCheckBoxCeliaco.setText("Apto Celíaco");
        jCheckBoxCeliaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCeliacoActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxCeliaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jCheckBoxVegetariano.setText("Apto Vegetariano");
        jCheckBoxVegetariano.setToolTipText("");
        jCheckBoxVegetariano.setVerifyInputWhenFocusTarget(false);
        jCheckBoxVegetariano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVegetarianoActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxVegetariano, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 20));

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setRows(5);
        jTextAreaDescripcion.setWrapStyleWord(true);
        jTextAreaDescripcion.setPreferredSize(new java.awt.Dimension(232, 80));
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 360, 90));

        jLabel5.setText("Descripcion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 70, -1));

        jLabel7.setText("Calorias:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, -1));

        txtCalorias.setForeground(new java.awt.Color(51, 51, 51));
        txtCalorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaloriasActionPerformed(evt);
            }
        });
        jPanel1.add(txtCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCaloriasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCaloriasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCaloriasActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPesoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnModificarActionPerformed
        Integer id = Integer.parseInt(txtID.getText());
        String nombre = txtNombre.getText();
        BigDecimal precio = new BigDecimal(txtPrecio.getText());
        Double peso = Double.parseDouble(txtPeso.getText());
        Double calorias = Double.parseDouble(txtCalorias.getText());
        Boolean aptoCeliaco = jCheckBoxCeliaco.isSelected();
        Boolean aptoVegetariano = jCheckBoxVegetariano.isSelected();
        Boolean aptoVegano = jCheckBoxVegano.isSelected();
        String descripcion = jTextAreaDescripcion.getText();

        Plato = new Plato(platoDto);

        itemMenuDao.modificarItemMenu();

    }// GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNombreActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtIDActionPerformed

    private void jCheckBoxVeganoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxVeganoActionPerformed
        if (jCheckBoxVegano.isSelected()) {
            jCheckBoxVegetariano.setSelected(true);
        }
    }// GEN-LAST:event_jCheckBoxVeganoActionPerformed

    private void jCheckBoxCeliacoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxCeliacoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCheckBoxCeliacoActionPerformed

    private void jCheckBoxVegetarianoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxVegetarianoActionPerformed
        if (!jCheckBoxVegetariano.isSelected()) {
            jCheckBoxVegano.setSelected(false);
        }
    }// GEN-LAST:event_jCheckBoxVegetarianoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificarPlato.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificarPlato.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificarPlato.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificarPlato.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificarPlato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox jCheckBoxCeliaco;
    private javax.swing.JCheckBox jCheckBoxVegano;
    private javax.swing.JCheckBox jCheckBoxVegetariano;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFechaAlta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField txtCalorias;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
