/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp.dsw.vista.cliente;

import java.math.BigDecimal;
import java.util.List;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

import com.mycompany.tp.dsw.controller.PedidoController;
import com.mycompany.tp.dsw.model.Estado;
import com.mycompany.tp.dsw.model.ItemPedido;
import com.mycompany.tp.dsw.model.Pedido;
import com.mycompany.tp.dsw.vista.util.HeaderFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmVerDetallesPedido extends javax.swing.JFrame {

    private String idPedido;
    private String idCliente;
    private PedidoController pedidoController;
    private Pedido pedido;

    public FrmVerDetallesPedido() {

    }

    public FrmVerDetallesPedido(String idPedido, String idCliente) {
        initComponents();
        pedidoController = new PedidoController();
        this.idPedido = idPedido;
        this.idCliente = idCliente;
        pedido = pedidoController.obtenerPedidoPorId(idPedido);
        this.setLocationRelativeTo(null);
        setearTituloTabla();
        initDatos();
    }

    public void initDatos() {
        List<ItemPedido> itemsPedidos = pedido.getItems();
        mostrarTabla(itemsPedidos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDetallesPedido = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnPagarMercadoPago = new javax.swing.JButton();
        btnPagarTransferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setPreferredSize(new java.awt.Dimension(518, 260));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 640, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 42, Short.MAX_VALUE));

        jPanel2.setPreferredSize(new java.awt.Dimension(518, 260));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 640, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 30, Short.MAX_VALUE));

        jPanel1.setLayout(new java.awt.BorderLayout());

        tbDetallesPedido.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {

                }));
        tbDetallesPedido.setRowHeight(25);
        jScrollPane1.setViewportView(tbDetallesPedido);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPagarMercadoPago.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPagarMercadoPago.setText("Pagar \nMercado Pago");
        btnPagarMercadoPago.setPreferredSize(new java.awt.Dimension(30, 30));
        btnPagarMercadoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMercadoPagoActionPerformed(evt);
            }
        });

        btnPagarTransferencia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPagarTransferencia.setText("Pagar Transferencia");
        btnPagarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(btnCancelar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnPagarTransferencia,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnPagarMercadoPago,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 640,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 640,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(49, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnPagarMercadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPagarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelar))
                                .addGap(12, 12, 12))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 15, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(314, 314, 314)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 16, Short.MAX_VALUE))));

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPagarTransferenciaActionPerformed
        if (pedido.getEstado().equals(Estado.ACEPTADO)) {
            FrmTransferencia transferenciaForm = new FrmTransferencia(idPedido, idCliente);
            transferenciaForm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Espere que su pedido sea aceptado por el restaurante");
        }
    }// GEN-LAST:event_btnPagarTransferenciaActionPerformed

    private void btnPagarMercadoPagoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPagarMercadoPagoActionPerformed
        if (pedido.getEstado().equals(Estado.ACEPTADO)) {
            FrmMercadoPago mercadoPagoForm = new FrmMercadoPago(idPedido, idCliente);
            mercadoPagoForm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Espere que su pedido sea aceptado por el restaurante");
        }
    }// GEN-LAST:event_btnPagarMercadoPagoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }// GEN-LAST:event_btnCancelarActionPerformed

    public void setearTituloTabla() {
        DefaultTableModel model = new DefaultTableModel();
        String[] titulo = { "PRODUCTO", "PRECIO UNITARIO", "CANTIDAD" };
        model.setColumnIdentifiers(titulo);
        tbDetallesPedido.setModel(model);

        // Personalizar el encabezado
        JTableHeader header = tbDetallesPedido.getTableHeader();
        header.setDefaultRenderer(new HeaderFormatter());
    }

    public void mostrarTabla(List<ItemPedido> itemsPedidos) {
        // Asegurarse de que la tabla tenga el modelo configurado
        if (tbDetallesPedido.getModel() == null || !(tbDetallesPedido.getModel() instanceof DefaultTableModel)) {
            setearTituloTabla(); // Configura el encabezado y el modelo si no está configurado
        }

        DefaultTableModel model = (DefaultTableModel) tbDetallesPedido.getModel(); // Recupera el modelo

        // Limpiar filas existentes
        model.setRowCount(0);

        BigDecimal total = BigDecimal.ZERO;
        if (itemsPedidos != null && !itemsPedidos.isEmpty()) {
            for (ItemPedido item : itemsPedidos) {
                Object[] fila = new Object[3];
                BigDecimal precio = item.getItemMenu().getPrecio();
                Integer cantidad = item.getCantidad();
                fila[0] = item.getItemMenu().getNombre();
                fila[1] = precio;
                fila[2] = cantidad;
                model.addRow(fila);

                total = total.add(precio.multiply(BigDecimal.valueOf(cantidad)));
            }
        }

        Object[] totalRow = { "TOTAL SIN RECARGO", total, "" };
        Object[] vaciaRow = { "", "", "" };
        model.addRow(vaciaRow);
        model.addRow(totalRow);

        tbDetallesPedido.setModel(model);
        // Ajustar el ancho de las columnas
        ajustarAnchoColumnas(tbDetallesPedido);
    }

    private void ajustarAnchoColumnas(JTable tabla) {
        // Itera sobre cada columna
        for (int columna = 0; columna < tabla.getColumnCount(); columna++) {
            TableColumn tableColumn = tabla.getColumnModel().getColumn(columna);
            int anchoPreferido = tabla.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(tabla, tableColumn.getHeaderValue(), false, false, -1, columna)
                    .getPreferredSize().width;

            tableColumn.setPreferredWidth(anchoPreferido);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVerDetallesPedido.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVerDetallesPedido.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVerDetallesPedido.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVerDetallesPedido.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVerDetallesPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagarMercadoPago;
    private javax.swing.JButton btnPagarTransferencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDetallesPedido;
    // End of variables declaration//GEN-END:variables
}
