/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp.dsw.view.itemMenu.plato;

import javax.swing.JOptionPane;

import com.mycompany.tp.dsw.dto.PlatoDto;
import com.mycompany.tp.dsw.memory.PlatoMemory;
import com.mycompany.tp.dsw.service.MemoryManager;
import com.mycompany.tp.dsw.view.itemMenu.FrmAgregarItem;

/**
 *
 * @author Usuario
 */
public class FrmAgregarPlato extends javax.swing.JDialog {

    private final PlatoMemory platoMemory;
    private final PlatoDto platoDto;
    private final MemoryManager memoryManager;

    public FrmAgregarPlato(PlatoDto platoDto, FrmAgregarItem agregarItemForm) {
        super(agregarItemForm, true);
        initComponents();
        this.platoDto = platoDto;
        memoryManager = MemoryManager.getInstance();
        platoMemory = memoryManager.getPlatoMemory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        txtCalorias = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jCheckBoxNO = new javax.swing.JCheckBox();
        jCheckBoxSI = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(440, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Calorias:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, -1));

        jLabel3.setText("Apto Celiaco:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 100, -1));

        txtCalorias.setForeground(new java.awt.Color(51, 51, 51));
        txtCalorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaloriasActionPerformed(evt);
            }
        });
        jPanel1.add(txtCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 100, -1));

        jLabel4.setText("Peso:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, -1));

        txtPeso.setForeground(new java.awt.Color(51, 51, 51));
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, -1));

        jCheckBoxNO.setText("NO");
        jCheckBoxNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNOActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jCheckBoxSI.setText("SI");
        jCheckBoxSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSIActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }// GEN-LAST:event_btnAtrasActionPerformed

    private void txtCaloriasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCaloriasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCaloriasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
        String calorias = txtCalorias.getText();
        String peso = txtPeso.getText();
        Boolean aptoCeliaco = jCheckBoxSI.isSelected();
        Boolean aptoVegano, aptoVegetariano;

        switch (platoDto.getCategoriaText().toLowerCase()) {
            case "comida vegana":
                aptoVegano = true;
                aptoVegetariano = true;
                break;
            case "comida vegetariana":
                aptoVegano = false;
                aptoVegetariano = true;
                break;
            default:
                aptoVegano = false;
                aptoVegetariano = false;
                break;
        }

        platoDto.setCaloriasText(calorias);
        platoDto.setPesoText(peso);
        platoDto.setAptoCeliaco(aptoCeliaco);
        platoDto.setAptoVegano(aptoVegano);
        platoDto.setAptoVegetariano(aptoVegetariano);

        platoMemory.registrarPlato(platoDto);
        JOptionPane.showMessageDialog(null, "Plato creado exitosamente");
        this.dispose();
    }// GEN-LAST:event_btnGuardarActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPesoActionPerformed

    private void jCheckBoxNOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxNOActionPerformed
        jCheckBoxSI.setSelected(false);
    }// GEN-LAST:event_jCheckBoxNOActionPerformed

    private void jCheckBoxSIActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxSIActionPerformed
        jCheckBoxNO.setSelected(false);
    }// GEN-LAST:event_jCheckBoxSIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarPlato(new PlatoDto(), new FrmAgregarItem(null, null, null)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox jCheckBoxNO;
    private javax.swing.JCheckBox jCheckBoxSI;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCalorias;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
